name = "sorbet"
version = "1.0.0"
description = "A simple key-value configuration format parser and formatter for Gleam with support for multi-line values."
licences = ["MIT"]
repository = { type = "github", user = "gleemers", repo = "glee-sorbet" }
# TODO: Add website
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
